package com.strongpoint.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNickName<M extends BaseNickName<M>> extends Model<M> implements IBean {

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return getStr("time");
	}

}
