package com.strongpoint.common.model;

import com.strongpoint.common.model.base.BaseNickName;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NickName extends BaseNickName<NickName> {
	public static final NickName dao = new NickName().dao();
}
