package com.strongpoint.common.model;

import com.strongpoint.common.model.base.BaseTeamUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamUser extends BaseTeamUser<TeamUser> {
	public static final TeamUser dao = new TeamUser().dao();
}
