package com.strongpoint.common.model;

import com.strongpoint.common.model.base.BaseTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Team extends BaseTeam<Team> {
	public static final Team dao = new Team().dao();
}
