package com.strongpoint.common.model;

import com.strongpoint.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	public User(Integer id, String pass) {
		// TODO Auto-generated constructor stub
		setId(id);
		setPass(pass);
	}

	public User() {
		// TODO Auto-generated constructor stub
	}
}
